package com.spring.push.vo;

import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.NotNull;
import java.util.Date;

public class DeviceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.id
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.sdk_version
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotBlank(message = "sdkVersion不能为空")
    private String sdkVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.client_id
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotBlank(message = "clientId不能为空")
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.client_type
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotBlank(message = "clientType不能为空")
    private String clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.cur_lat
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotNull(message = "curLat不能为空")
    private Double curLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.cur_lon
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotNull(message = "curLon不能为空")
    private Double curLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_name
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotBlank(message = "deviceName不能为空")
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.faze_end_time
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private String fazeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.faze_start_time
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private String fazeStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.faze_status
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private Boolean fazeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.last_change_time
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private Date lastChangeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.net_type
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotBlank(message = "netType不能为空")
    private String netType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.os_name
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    @NotBlank(message = "osName不能为空")
    private String osName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.p_status
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private Boolean pStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.api_key_id
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private Integer apiKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.admin_code
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private String adminCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.use_key
     *
     * @mbggenerated Mon Jul 09 10:12:16 CST 2018
     */
    private String useKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.city_code
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    private String cityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.id
     *
     * @return the value of device_info.id
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.id
     *
     * @param id the value for device_info.id
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.sdk_version
     *
     * @return the value of device_info.sdk_version
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getSdkVersion() {
        return sdkVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.sdk_version
     *
     * @param sdkVersion the value for device_info.sdk_version
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setSdkVersion(String sdkVersion) {
        this.sdkVersion = sdkVersion == null ? null : sdkVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.client_id
     *
     * @return the value of device_info.client_id
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.client_id
     *
     * @param clientId the value for device_info.client_id
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.client_type
     *
     * @return the value of device_info.client_type
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.client_type
     *
     * @param clientType the value for device_info.client_type
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.cur_lat
     *
     * @return the value of device_info.cur_lat
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public Double getCurLat() {
        return curLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.cur_lat
     *
     * @param curLat the value for device_info.cur_lat
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setCurLat(Double curLat) {
        this.curLat = curLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.cur_lon
     *
     * @return the value of device_info.cur_lon
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public Double getCurLon() {
        return curLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.cur_lon
     *
     * @param curLon the value for device_info.cur_lon
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setCurLon(Double curLon) {
        this.curLon = curLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_name
     *
     * @return the value of device_info.device_name
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_name
     *
     * @param deviceName the value for device_info.device_name
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.faze_end_time
     *
     * @return the value of device_info.faze_end_time
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getFazeEndTime() {
        return fazeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.faze_end_time
     *
     * @param fazeEndTime the value for device_info.faze_end_time
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setFazeEndTime(String fazeEndTime) {
        this.fazeEndTime = fazeEndTime == null ? null : fazeEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.faze_start_time
     *
     * @return the value of device_info.faze_start_time
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getFazeStartTime() {
        return fazeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.faze_start_time
     *
     * @param fazeStartTime the value for device_info.faze_start_time
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setFazeStartTime(String fazeStartTime) {
        this.fazeStartTime = fazeStartTime == null ? null : fazeStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.faze_status
     *
     * @return the value of device_info.faze_status
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public Boolean getFazeStatus() {
        return fazeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.faze_status
     *
     * @param fazeStatus the value for device_info.faze_status
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setFazeStatus(Boolean fazeStatus) {
        this.fazeStatus = fazeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.last_change_time
     *
     * @return the value of device_info.last_change_time
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public Date getLastChangeTime() {
        return lastChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.last_change_time
     *
     * @param lastChangeTime the value for device_info.last_change_time
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setLastChangeTime(Date lastChangeTime) {
        this.lastChangeTime = lastChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.net_type
     *
     * @return the value of device_info.net_type
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getNetType() {
        return netType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.net_type
     *
     * @param netType the value for device_info.net_type
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setNetType(String netType) {
        this.netType = netType == null ? null : netType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.os_name
     *
     * @return the value of device_info.os_name
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getOsName() {
        return osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.os_name
     *
     * @param osName the value for device_info.os_name
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setOsName(String osName) {
        this.osName = osName == null ? null : osName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.p_status
     *
     * @return the value of device_info.p_status
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public Boolean getpStatus() {
        return pStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.p_status
     *
     * @param pStatus the value for device_info.p_status
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setpStatus(Boolean pStatus) {
        this.pStatus = pStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.api_key_id
     *
     * @return the value of device_info.api_key_id
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public Integer getApiKeyId() {
        return apiKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.api_key_id
     *
     * @param apiKeyId the value for device_info.api_key_id
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setApiKeyId(Integer apiKeyId) {
        this.apiKeyId = apiKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.admin_code
     *
     * @return the value of device_info.admin_code
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getAdminCode() {
        return adminCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.admin_code
     *
     * @param adminCode the value for device_info.admin_code
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setAdminCode(String adminCode) {
        this.adminCode = adminCode == null ? null : adminCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.use_key
     *
     * @return the value of device_info.use_key
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getUseKey() {
        return useKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.use_key
     *
     * @param useKey the value for device_info.use_key
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setUseKey(String useKey) {
        this.useKey = useKey == null ? null : useKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.city_code
     *
     * @return the value of device_info.city_code
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.city_code
     *
     * @param cityCode the value for device_info.city_code
     *
     * @mbggenerated Tue Aug 21 18:55:58 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }
}